/*
This file is automatically generated
DefaultTheme
Header
*/

#ifndef DefaultTheme__H
#define DefaultTheme__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "FT_DataTypes.h"
#include "Ft_Esd_Theme.h"

ESD_FUNCTION(DefaultTheme, Type = Ft_Esd_Theme *, Include = "DefaultTheme.h", Category = _GroupUserResources, Icon = ":/icons/palette.png")
Ft_Esd_Theme *DefaultTheme();

#endif /* DefaultTheme__H */

/* end of file */
