/*
This file is automatically generated
DefaultTheme
C Source
*/

#include "DefaultTheme.h"

static Ft_Esd_Theme DefaultTheme__Instance = {
	.ClearColor = 0x212121,
	.BackColor = 0x151515,
	.TextColor = 0xffffff,
	.ButtonTextColor = 0xffffff,
	.DefaultColor = 0x6b6b6b,
	.PrimaryColor = 0xff7f3f,
};

Ft_Esd_Theme *DefaultTheme()
{
	return &DefaultTheme__Instance;
}

/* end of file */
