/*
This file is automatically generated
DO NOT MODIFY BY HAND
MainPage
Header
*/

#ifndef MainPage__H
#define MainPage__H

#include "Ft_Esd.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_Layout_Display.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_Layout_Linear.h"
#include "Ft_Esd_Layout_Stretch.h"
#include "Ft_Esd_PushButton.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_Widget.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_UI(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define MainPage_CLASSID 0x26757037
ESD_SYMBOL(MainPage_CLASSID, Type = esd_classid_t)

ESD_WIDGET(MainPage, Include = "MainPage.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_VARIABLE(Variable_2, Type = int, Private)
	int Variable_2;
	ESD_VARIABLE(Variable, Type = int, Private)
	int Variable;
	Ft_Esd_Layout_Display Fill_Display;
	Ft_Esd_Layout_Linear Ft_Esd_Layout_Vertical;
	Ft_Esd_Layout_Fixed Fixed_Positioning;
	Ft_Esd_Label ESD_Label;
	Ft_Esd_Layout_Stretch Ft_Esd_Layout_Stretch_4;
	Ft_Esd_Layout_Linear Ft_Esd_Layout_Horizontal;
	Ft_Esd_PushButton button_right_move;
	Ft_Esd_PushButton button_left_move;
	Ft_Esd_Layout_Stretch Ft_Esd_Layout_Stretch;
} MainPage;

void MainPage__Initializer(MainPage *context);

ESD_SLOT(End)
void MainPage_End(MainPage *context);

ESD_SLOT(Update)
void MainPage_Update(MainPage *context);

#endif /* MainPage__H */

/* end of file */
