/*
This file is automatically generated
DO NOT MODIFY BY HAND
MainPage
C Source
*/

#include "MainPage.h"

extern void Ft_Esd_Noop(void *context);

static ft_int16_t MainPage_ESD_Label_Font__Property(void *context) { return 31; }
static const char * MainPage_ESD_Label_Text__Property(void *context) { return "ESD"; }
static const char * MainPage_button_right_move_Text__Property(void *context) { return "<<"; }
static const char * MainPage_button_left_move_Text__Property(void *context) { return ">>"; }

static Ft_Esd_WidgetSlots s_MainPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))MainPage_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))MainPage_End,
};


void MainPage__Fill_Display__Initializer(MainPage *context)
{
	Ft_Esd_Layout_Display *object = &context->Fill_Display;
	Ft_Esd_Layout_Display__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 0;
	object->Widget.LocalHeight = 0;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void MainPage__Ft_Esd_Layout_Vertical__Initializer(MainPage *context)
{
	Ft_Esd_Layout_Linear *object = &context->Ft_Esd_Layout_Vertical;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 0;
	object->Widget.LocalHeight = 0;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Display);
}

void MainPage__Fixed_Positioning__Initializer(MainPage *context)
{
	Ft_Esd_Layout_Fixed *object = &context->Fixed_Positioning;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 302;
	object->Widget.LocalY = 18;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Ft_Esd_Layout_Vertical);
}

void MainPage__ESD_Label__Initializer(MainPage *context)
{
	Ft_Esd_Label *object = &context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = -374;
	object->Widget.LocalHeight = 0;
	object->Font = MainPage_ESD_Label_Font__Property;
	object->Text = MainPage_ESD_Label_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void MainPage__Ft_Esd_Layout_Stretch_4__Initializer(MainPage *context)
{
	Ft_Esd_Layout_Stretch *object = &context->Ft_Esd_Layout_Stretch_4;
	Ft_Esd_Layout_Stretch__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 0;
	object->Widget.LocalHeight = 0;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Ft_Esd_Layout_Vertical);
}

void MainPage__Ft_Esd_Layout_Horizontal__Initializer(MainPage *context)
{
	Ft_Esd_Layout_Linear *object = &context->Ft_Esd_Layout_Horizontal;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 0;
	object->Widget.LocalHeight = 60;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_FILLCENTER;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Ft_Esd_Layout_Vertical);
}

void MainPage__button_right_move__Initializer(MainPage *context)
{
	Ft_Esd_PushButton *object = &context->button_right_move;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 433;
	object->Widget.LocalY = 100;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 200;
	object->Text = MainPage_button_right_move_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Ft_Esd_Layout_Horizontal);
}

void MainPage__button_left_move__Initializer(MainPage *context)
{
	Ft_Esd_PushButton *object = &context->button_left_move;
	Ft_Esd_PushButton__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 198;
	object->Widget.LocalY = 230;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 60;
	object->Text = MainPage_button_left_move_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Ft_Esd_Layout_Horizontal);
}

void MainPage__Ft_Esd_Layout_Stretch__Initializer(MainPage *context)
{
	Ft_Esd_Layout_Stretch *object = &context->Ft_Esd_Layout_Stretch;
	Ft_Esd_Layout_Stretch__Initializer(object);
	object->Owner = context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 0;
	object->Widget.LocalHeight = 0;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Ft_Esd_Layout_Vertical);
}

void MainPage__Initializer(MainPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = MainPage_CLASSID;
	context->Widget.Slots = &s_MainPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Variable_2 = 0L;
	context->Variable = 0L;
	MainPage__Fill_Display__Initializer(context);
	MainPage__Ft_Esd_Layout_Vertical__Initializer(context);
	MainPage__Fixed_Positioning__Initializer(context);
	MainPage__ESD_Label__Initializer(context);
	MainPage__Ft_Esd_Layout_Stretch_4__Initializer(context);
	MainPage__Ft_Esd_Layout_Horizontal__Initializer(context);
	MainPage__button_right_move__Initializer(context);
	MainPage__button_left_move__Initializer(context);
	MainPage__Ft_Esd_Layout_Stretch__Initializer(context);
}

void MainPage_Update__Builtin(MainPage *context)
{
	void *owner = context->Owner;
	int left = context->Variable_2;
	int right = context->Variable;
	int update_variable = left + right;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->ESD_Label, update_variable);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void MainPage_End(MainPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Display); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Ft_Esd_Layout_Vertical); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Positioning); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Ft_Esd_Layout_Stretch_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Ft_Esd_Layout_Horizontal); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->button_right_move); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->button_left_move); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Ft_Esd_Layout_Stretch); 
}

void MainPage_Update(MainPage *context)
{
	void *owner = context->Owner;
	ft_bool_t if_1 = Ft_Esd_PushButton_Pushing(&context->button_left_move);
	if (if_1)
	{
		int set_variable = 1L;
		context->Variable = set_variable;
	}
	else
	{
	}
	ft_int16_t set_variable_3 = context->ESD_Label.Widget.LocalX;
	context->Variable_2 = set_variable_3;
	ft_bool_t if_2 = Ft_Esd_PushButton_Pushing(&context->button_right_move);
	if (if_2)
	{
		int set_variable_2 = -1L;
		context->Variable = set_variable_2;
	}
	else
	{
	}
	MainPage_Update__Builtin(context);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	MainPage Instance;
} MainPage__ESD;


void *MainPage__Create__ESD()
{
	MainPage__ESD *context = (MainPage__ESD *)malloc(sizeof(MainPage__ESD));
	MainPage__Initializer(&context->Instance);
	context->Instance.Owner = context;
	return context;
}

void MainPage__Destroy__ESD(void *context)
{
	free(context);
}

void MainPage__Set_Variable_2__ESD(void *context, int value) { ((MainPage__ESD *)context)->Instance.Variable_2 = value; }
void MainPage__Set_Variable__ESD(void *context, int value) { ((MainPage__ESD *)context)->Instance.Variable = value; }

#endif /* ESD_SIMULATION */

/* end of file */
